
name: Check
description: Check a username against our lists of groups

inputs:
  user_login:
    description: The GitHub username to check
    required: true

  maintainers:
    description: The base64 encoded list of maintainers
    required: false

outputs:
  ci_approved_label:
    description: Label that indicates CI approval
    value: ${{ steps.maintainer.outputs.check }}

runs:
  using: composite
  steps:
    - name: Maintainer
      id: maintainer
      if: inputs.maintainers != ''
      shell: bash
      run: |
        echo "check=$(echo ${{ inputs.maintainers }} | base64 --decode | jq --arg u ${{ inputs.user_login }} -r 'to_entries[] | select(.value[] == $u) | .key')" >> "$GITHUB_OUTPUT"

    - name: Add CI Approved Label
      if: steps.maintainer.outputs.check != ''
      shell: bash
      run: |
        gh pr edit ${{ github.event.pull_request.html_url }} --add-label ${{ steps.approval_check.outputs.ci_approved_label }}