name: CI Approval Check

on:
  pull_request_target:
    types:
      - opened
      - labeled
  issue_comment:
    types:
      - created

jobs:
  ci_approval:
    if: github.event.action == 'opened'
    uses: ./.github/workflows/reusable_ci_approval.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      user_login: ${{ github.event.pull_request.user.login }}
      team_name: ''
    secrets:
      approved_users: ${{ secrets.CI_APPROVED_USERS }}
      app_id: ${{ secrets.APP_ID }}
      app_key: ${{ secrets.APP_KEY }}

  check_labels:
    needs: chatops
    if: |
      always() &&
      (github.event.action == 'labeled' ||
       needs.chatops.result == 'success')
    uses: ./.github/workflows/reusable_label_check.yml
    permissions:
      pull-requests: write
    with:
      labels: ${{ github.event.action == 'labeled' && format('[{0}]', toJson(github.event.label.name)) || '["ci-approved-maintainer"]' }}
      user_login: ${{ github.event.sender.login }}
      pr_number: ${{ github.event.pull_request.number || github.event.issue.number }}
      label_bot: johnsonaj-bot[bot]
      team_name: test-maintainer-team
    secrets:
      approved_users: ${{ secrets.CI_APPROVED_USERS }}
      token: ${{ secrets.GITHUB_TOKEN }}
      app_id: ${{ secrets.APP_ID }}
      app_key: ${{ secrets.APP_KEY }}

  chatops:
    if: github.event_name == 'issue_comment'
    uses: ./.github/workflows/reusable_chatops.yml
    permissions:
      pull-requests: write
    with:
      chat_command: '/test'
      comment: ${{ github.event.comment.body }}
      username: ${{ github.event.comment.user.login }}
      issue_number: ${{ github.event.issue.number }}
      team_name: test-maintainer-team
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      app_id: ${{ secrets.APP_ID }}
      app_key: ${{ secrets.APP_KEY }}

  # starts tctest workflow.

  start_tc_test:
    needs: check_labels
    if: |
      always() &&
      needs.check_labels.result == 'success' &&
      needs.check_labels.outputs.has_approved_label == 'true'
    uses: ./.github/workflows/reusable_start_tc_test.yml
    permissions:
      pull-requests: write
    with:
      has_approved_label: ${{ needs.check_labels.outputs.has_approved_label }}
      pr_number: ${{ github.event.pull_request.number || github.event.issue.number }}
      repository: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      app_id: ${{ secrets.APP_ID }}
      app_key: ${{ secrets.APP_KEY }}
