name: CI Approval Check

on:
  pull_request_target:
    types:
      - opened
      - labeled

jobs:
  ci_approval:
    if: github.event.action == 'opened'
    uses: ./.github/workflows/reusable_ci_approval.yml
    permissions:
      contents: read
      pull-requests: write
    with:
      user_login: ${{ github.event.pull_request.user.login }}
    secrets:
      maintainers: ${{ secrets.CI_APPROVED_USERS }}
      token: ${{ secrets.GITHUB_TOKEN }}

  start_tc_test:
    if: contains(github.event.pull_request.labels.*.name, 'ci-approved-maintainer')
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment Test Started
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" \
            --repo "${{ github.repository }}" \
            --body "Test started."

