on:
  workflow_call:
    inputs:
      user_login:
        required: true
        type: string
    secrets:
      approved_users:
        required: true
      app_id:
        required: true
      app_key:
        required: true

jobs:
  ci_approval_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app_token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_key }}
      - name: Checkout Approval Check
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: .github/actions/check

      - name: Approval Check
        id: approval_check
        uses: ./.github/actions/check
        with:
          user_login: ${{ inputs.user_login }}
          approved_users: ${{ secrets.approved_users }}

      - name: Label PR if Approved
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app_token.outputs.token }}
        run: |
          label="${{ steps.approval_check.outputs.ci_approved_label }}"
          if [ -z "$label" ]; then
            label="ci-needs-mainainer-review"
          fi
          gh pr edit ${{ github.event.pull_request.html_url }} --add-label "$label"
