on:
  workflow_call:
    inputs:
      has_approved_label:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  start_tc_test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Comment test status
        env:
          GH_TOKEN: ${{ secrets.token }}
          HAS_APPROVED_LABEL: ${{ inputs.has_approved_label }}
          PR_NUMBER: ${{ inputs.pr_number }}
          GITHUB_REPOSITORY: ${{ inputs.repository }}
        run: .github/scripts/start_tc_test.sh
