on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
    secrets:
      maintainers:
        required: true
    outputs:
      has_label:
        description: Whether label is present
        value: ${{ steps.label_check.outputs.check }}

jobs:
  label_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        id: label_check
        shell: bash
        run: |
          $MAINTAINERS=$(echo ${{ secrets.maintainers }} | base64 --decode)
          echo "check=$(jq -n --argjson a $MAINTAINERS --argjson b ${{ inputs.labels }} -r 'any($b[]; . as $x | $a | index($x) != null)')" >> "$GITHUB_OUTPUT"