on:
  workflow_call:
    inputs:
      labels:
        required: true
        type: string
    secrets:
      approved_users:
        required: true
    outputs:
      has_approved_label:
        description: Whether label is present
        value: ${{ jobs.label_check.outputs.has_label }}

jobs:
  label_check:
    runs-on: ubuntu-latest
    outputs:
      has_label: ${{ steps.label_check.outputs.check }}
    steps:
      - name: Check Labels
        id: label_check
        shell: bash
        env:
          LABELS_JSON: ${{ inputs.labels }}
          APPROVED_USERS_B64: ${{ secrets.approved_users }}
        run: |
          APPROVED_USERS_JSON="$(echo "$APPROVED_USERS_B64" | base64 --decode)"
          echo "check=$(jq -n --argjson approved_users "$APPROVED_USERS_JSON" --argjson labels "$LABELS_JSON" -r 'any($labels[]; . as $label | ($approved_users | keys | index($label)) != null)')" >> "$GITHUB_OUTPUT"
