on:
  workflow_call:
    inputs:
      user_login:
        required: true
        type: string
    secrets:
      maintainers:
        required: true
      token:
        required: true

jobs:
  ci_approval_check:
    runs-on: ubuntu-latest
    outputs:
        ci_approved_label: ${{ steps.approval_check.outputs.ci_approved_label }}
    steps:
      - name: Checkout Approval Check
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: .github/actions/check

      - name: Approval Check
        id: approval_check
        uses: ./.github/actions/check
        with:
          user_login: ${{ inputs.user_login }}
          maintainers: ${{ secrets.maintainers }}

  label_pr:
    needs: ci_approval_check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout label
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          sparse-checkout: .github/actions/label

      - name: Label PR
        id: add_label
        uses: ./.github/actions/label
        with:
          label: ${{ needs.ci_approval_check.outputs.ci_approved_label }}
          github_url: ${{ github.event.pull_request.html_url }}
        env:
          GH_TOKEN: ${{ secrets.token }}
