on:
  workflow_call:
    inputs:
      has_approved_label:
        required: true
        type: string
      pr_number:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      token:
        required: true
      app_id:
        required: true
      app_key:
        required: true

jobs:
  start_run:
    runs-on: ubuntu-latest
    steps:
      - name: Start tctest
        shell: bash
        run: | 
          echo "placeholder for starting tctest. TO BE IMPLEMENTED"
          echo "Starting tctest for PR #${{ inputs.pr_number }} in repo ${{ inputs.repository }} with approved label: ${{ inputs.has_approved_label }}"
  comment_status:
    runs-on: ubuntu-latest
    needs: start_run
    permissions:
      pull-requests: write
    steps:
      - uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app_token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.app_key }}
      - name: Checkout script repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: johnsonaj/test-actions
          token: ${{ steps.app_token.outputs.token }}
          path: script-repo
      - name: Comment test status
        env:
          GH_TOKEN: ${{ secrets.token }}
          HAS_APPROVED_LABEL: ${{ inputs.has_approved_label }}
          PR_NUMBER: ${{ inputs.pr_number }}
          GITHUB_REPOSITORY: ${{ inputs.repository }}
        run: script-repo/.github/scripts/start_tc_test.sh
